### ISSUE TITLE
Receive "major/minor" values from beacons

### ISSUE THREAD

**Issue by linslin** [randdusing/BluetoothLE#103]
Hey,

i cant figure out where to find "major/minor" values for a scanned beacon. How to receive those values?

**Comment by linslin** [comment]
Any update on this?

**Comment by randdusing** [comment]
Sorry, forgot about this one over the holidays. Hopefully I can take a look in a few days.

**Comment by randdusing** [comment]
Actually upon looking into it further, Estimote doesn't seem to support simulating iBeacons on Android devices. Nor can I do it on my Macbook now that I'm running Yosemite.  Two Android devices support simulating iBeacons according to http://altbeacon.github.io/android-beacon-library/, but unfortunately I don't have either device.

I'm pretty sure iBeacons and the CoreBluetooth classes don't get along very well. The CoreLocation classes must be used instead.

**Comment by wouterbulten** [comment]
I also ran into this issue today: the advertisement field is empty for iBeacons in combination with iOS. Any plans on using the CoreLocation lib as an extension to support iBeacons? Would be very usefull to have this functionality!

**Comment by randdusing** [comment]
Closing this one. Best bet is to use the ibeacon plugin: https://github.com/petermetz/cordova-plugin-ibeacon I don't plan on supporting this within my plugin.
