### ISSUE TITLE
Heart Rate Example

### ISSUE THREAD

**Issue by ltbmedia** [randdusing/BluetoothLE#116]
HI, thanks for the plugin and I have managed to get your example working.

Do you have a simple heart rate example where you can read the value on screen, the descriptor byte value bit is confusing if that is indeed the correct thing I should be looking at.

Thanks for any help,

Daniel

**Comment by joserogerio** [comment]
Example: 
   var bytes = bluetoothle.encodedStringToBytes(obj.value);

   //Check for data
   if (bytes.length == 0)
   {
      console.log("Subscription result had zero length data");
      return;
   }

   //Get the first byte that contains flags
   var flag = bytes[0];

   //Check if u8 or u16 and get heart rate
   var hr;
   if ((flag & 0x01) == 1)
   {
      var u16bytes = bytes.buffer.slice(1, 3);
      var u16 = new Uint16Array(u16bytes)[0];
      hr = u16;
   }
   else
   {
      var u8bytes = bytes.buffer.slice(1, 2);
      var u8 = new Uint8Array(u8bytes)[0];
      hr = u8;
   }
   console.log("Heart Rate: " + hr);

**Comment by randdusing** [comment]
Added this to the readme
