### ISSUE TITLE
Phonegap build change log (version log)

### ISSUE THREAD

**Issue by diverJohn** [randdusing/BluetoothLE#120]
Rand,

I noticed that you just posted a new version, 2.0.0, to Phonegap build.   The previous version was 1.0.6.   Is there a log of the changes between 1.0.6 to 2.0.0 or between each change?   I would like to use the new and improved version but I am not sure what has changed internally or at the interface.

Thanks,
John

**Comment by randdusing** [comment]
Have change log going on by local repository, so closing this now
