### ISSUE TITLE
Scanning for devices if app is open?

### ISSUE THREAD

**Issue by dibari** [randdusing/BluetoothLE#128]
I have a use case for an app - a popup should be displayed whenever a specific bluetooth device (by name) is available.  That would basically require the plugin to be scanning for the device if the app is open.  Seems like a very inefficient use case, but I wanted your opinion.  Is this reasonable do?  I'm assuming it would drain battery quickly, at the least.

**Comment by randdusing** [comment]
Yep, I don't remember the iOS documentation mentioning long scans, but the Android documentation specifically mentions not to scan longer than necessary.
