### ISSUE TITLE
IPhone 6 initialization fails

### ISSUE THREAD

**Issue by dibari** [randdusing/BluetoothLE#133]
I've started testing my app with an iphone 6, and the initialization seems to fail.  It simply through an error with an empty object, so I'm not sure what's happening.  Any ideas what could be causing it?  Everything has been working fine with my iphone 4s, which was running ios 7.  The iphone 6 is using ios 8

**Comment by randdusing** [comment]
Do you get any sort of error message?

**Comment by dibari** [comment]
I realized I hadn't installed the plugin via cordova, so initialization was just failing without any message.   Everything is working great with the plugin though.  Thanks for being responsive and thanks for the plugin!

**Comment by randdusing** [comment]
Glad you figured it out. I've done that a few times as well.
