### ISSUE TITLE
isDiscovered returns null after reconnect

### ISSUE THREAD

**Issue by mpedersen15** [randdusing/BluetoothLE#141]
Hi Rand,

I'm working on creating some robustness when connecting to my BLE peripheral, and want to make sure I can reconnect and then write to the device after it gets disconnected. The isDiscovered function works perfectly after the initial connection to the peripheral, but after I reconnect successfully, isDiscovered only seems to return null. Could this be a bug of some kind?

Thanks for the help and the great plugin!

EDIT: This problem only exists on Android, since iOS has a different procedure for service and characteristic discover!

**Comment by randdusing** [comment]
Thanks for the bug report. I've found the issue on Android and should be very similar on iOS. I should be wrapping up the next version tonight.

**Comment by randdusing** [comment]
Oops forgot iOS discovery works much differently and this shouldn't be possible on iOS. Was your original bug report was only for Android?

**Comment by mpedersen15** [comment]
Yep you're correct, only for Android. iOS has been working pretty consistently for me! Thanks for checking this out!

**Comment by randdusing** [comment]
Should be good to go now.

**Comment by mpedersen15** [comment]
Awesome thanks!
