### ISSUE TITLE
bluetoothle.rssi never gets callback or error? (iOS)

### ISSUE THREAD

**Issue by matthewkremer** [randdusing/BluetoothLE#149]
So after connecting to a device and getting the status of "connected" I try booting off a call to ``bluetoothle.rssi()`` with the address of the device and nothing happens.

No error, no success callback, no error callback, nothing.

Any ideas? Thanks!

**Comment by matthewkremer** [comment]
Interesting...I thought this was due to the problems with the callback in iOS 8.0 so I changed some code, wouldn't compile, replaced the ``.m`` file with the original, and it worked...

Now I'm just stumped, oh well! At least it's working :)

**Comment by randdusing** [comment]
Glad, you got it figured out. Let me know if it reoccurs!

**Comment by ArMouReR** [comment]
I have strange problem IOS8 - on one device everything works without problem.
On another device: the same problem as described here: no callback and no error...
Any idea how can I debug it ?

Thanks...
