### ISSUE TITLE
Phones not detecting

### ISSUE THREAD

**Issue by NorrisBolduc** [randdusing/BluetoothLE#166]
Hi ,

When i scan for devices i was able to get health band but nearby Bluetooth enabled phones are not detecting ?? Is there any settings needs to be tweaked ??

**Comment by randdusing** [comment]
Only devices advertising Bluetooth LE will show up. Usually phones won't advertise as Bluetooth LE as far as I can tell. My iPhone and Nexus tablet never show up.

**Comment by NorrisBolduc** [comment]
Thanks for the info . Is there an way to make my phones to advertise as BLE ??

**Comment by randdusing** [comment]
I think you would need to create or download an app that advertises in BLE.

**Comment by NorrisBolduc** [comment]
Thank you for the info ! Will explore on that .
