### ISSUE TITLE
Write to configure iBeacon

### ISSUE THREAD

**Issue by asafshefi** [randdusing/BluetoothLE#175]
Hi,

I'm trying to use this great plugin to configure some parameters in iBeacon devices.
The iBeacon device supply an android and ios app that can update these parameters provided you enter a password. I did not see any support for entering a password for writing to the device.
Is it possible? when I try the regular write it fails with "Unable to write on return"

Thanks in advance,

Asaf

**Comment by randdusing** [comment]
On iOS, iBeacons aren't really supported with this code since iOS uses another set of code to interact with them. Maybe check out https://github.com/petermetz/cordova-plugin-ibeacon instead
