### ISSUE TITLE
Can not get UUID

### ISSUE THREAD

**Issue by metaljack** [randdusing/BluetoothLE#176]
Hi,

I can't seem to work out why I cannot find the UUID of my BLE device. Here is what is returned on Scan Success:
<code>
"Start Scan Success : {\"advertisement\":\"AgEaGv9MAAIVWlUP7mXaMxH2Rd9WH2Y9YQAAAADJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\",\"rssi\":-55,\"status\":\"scanResult\",\"address\":\"00:1A:7D:DA:71:08\",\"name\":\"CSR8510 A10\"}"
</code>

I thought by default it connected with UUID rather than MAC.

Checked UUID with a different scanner app and it appears fine.

Any help would be great.
Thanks,
Phil

**Comment by randdusing** [comment]
On Android, the address looks like a MAC. On iOS, it looks like a UUID. Either way, the address you get from the scan is the one you should pass to connect.
