### ISSUE TITLE
Allow duplicate advertisement packets during scan

### ISSUE THREAD

**Issue by andySigler** [randdusing/BluetoothLE#184]
Thanks for the great library! I am building an application that would greatly benefit from the ability to pick up duplicate advertising packets from a peripheral while scanning. [I have read that on iOS this can be specified](https://developer.apple.com/library/prerelease/ios/documentation/CoreBluetooth/Reference/CBCentralManager_Class/index.html#//apple_ref/doc/constant_group/Peripheral_Scanning_Options). Sorry if this feature already exists, I have not been able to find any documentation of it.

**Comment by randdusing** [comment]
Should have this finished shortly, but I'm kind of confused. I'm not exactly sure what CBCentralManagerScanOptionAllowDuplicatesKey does. If I set it to No, I still get multiple scan results from devices. If I set it to Yes, I get multiple scan results from devices, but seemingly a lot more.
