### ISSUE TITLE
Move the Android source to use SweetBlue

### ISSUE THREAD

**Issue by kgillespieanaren** [randdusing/BluetoothLE#186]
Android BLE stack is going to terrible to directly support for the foreseeable future. I would highly recommend that the BluetoothLE plugin adopt using the SweetBlue library for Android. It essential tries to save a programmer from all the ugliness and quirkiness of the Android BLE stack by wrapping it in a state controller system and checking system. It appears to be incredibly robust and improves the over all experience of using BLE on android.

Check it out

https://github.com/iDevicesInc/SweetBlue

**Comment by randdusing** [comment]
@kgillespieanaren It seems like you need to buy a license if you plan to use SweetBlue for commercial purposes.
