### ISSUE TITLE
Adroid Target API

### ISSUE THREAD

**Issue by furnaceX** [randdusing/BluetoothLE#187]
In the "Installation Quirks (Android)" you state: "The latest version of the plugin requires you to set the Android target API to 21."

Does this mean I can use the latest Cordova install (requires android 22 SDK), but just set  android:targetSdkVersion="21".  Or do I need a previous version of Cordova and the android 21 SDK?

**Comment by randdusing** [comment]
Anything 21 or higher is fine. I need to change that to a "Android target API to a minimum of 21."
