### ISSUE TITLE
Enable on Android

### ISSUE THREAD

**Issue by randdusing** [randdusing/BluetoothLE#194]
Enable on Android doesn't seem to use the original initialize callback

**Comment by antrjec** [comment]
Hi Randdusing. How I can use notify (recieve data)

**Comment by randdusing** [comment]
You are supposed to be able to listen to the original initialize success callback, but it didn't seem to be working when I was testing the Angular wrapper. It may be an issue with just the wrapper, but I need to look into it some more.

**Comment by randdusing** [comment]
Issue is actually with the Angular Wrapper not handling the initialize callbacks properly.
