### ISSUE TITLE
initialize tear-down?

### ISSUE THREAD

**Issue by rclai** [randdusing/BluetoothLE#197]
IT says here https://github.com/randdusing/BluetoothLE#initialize that the initialize will be called over and over whether the bluetooth is enabled or disabled, is there no way to tear it down and use it only on demand?

**Comment by randdusing** [comment]
It just needs to be called once before any other Bluetooth calls are made.
Android and iOS don't provide any functions to tear down Bluetooth, but it
doesn't seem to be an issue.

**Comment by rclai** [comment]
Okay, it's just that I hope that this is not a battery-drainer.

**Comment by randdusing** [comment]
As long as you aren't actively using scanning, it shouldn't be a battery drainer.
