### ISSUE TITLE
is this plugin supports wondows  8.1?

### ISSUE THREAD

**Issue by tdigambar** [randdusing/BluetoothLE#198]
i want to use this plugin on windows 8.1. is it possible any way to use this plugin?

**Comment by randdusing** [comment]
Another user has added some code, but I don't support it myself yet. I would like to go through it and make it more consistent with the rest of the code, but my project doesn't justify it and I'm low on time. If you search the issues, you may be able to find some help

**Comment by tdigambar** [comment]
hi randdusing, thank you for the reply.
