### ISSUE TITLE
Not scanning unpaired device in Android

### ISSUE THREAD

**Issue by irfan8812** [randdusing/BluetoothLE#207]
Hello,

When we click on Start Scan then Retrieve Connected it only shows the paired Bluetooth IDs. Please give some suggestion how it will show all pair and unpair Bluetooth IDs.

**Comment by randdusing** [comment]
What Android version are you on?

**Comment by irfan8812** [comment]
We are using android 5.0.2

**Comment by randdusing** [comment]
Do you see anything in the logs about scan results?

**Comment by irfan8812** [comment]
The value of obj.status is 'scanStarted' everytime. It doesn't go inside
if(obj. status == "scanResult")  block. So it's not add any new device
through addDevice().

**Comment by randdusing** [comment]
I mean from LogCat, then you should see if the results are even appearing at a lower level.

**Comment by irfan8812** [comment]
[image: Inline image 1]

Regards,
Mohammad Irfan
Software Engineer , Interbiz Consulting
Phone: (+91-7752) 401-858, 261-189; (+1-602) 218-4062
Web: www.interbizconsulting.com ‘success through synergy’

**Comment by randdusing** [comment]
Your image didn't come through although text input would be easier to copy and paste if needed.

**Comment by randdusing** [comment]
Reopen if you still need help
