### ISSUE TITLE
Question: Version tags (2.1.2 on npmjs.com) where do they come from?

### ISSUE THREAD

**Issue by aroncal** [randdusing/BluetoothLE#212]
I can't see in this project in github the version numbering i can see on [npmjs](https://www.npmjs.com/package/com.randdusing.bluetoothle), actually **version 2.1.2**- Where does that number come from? I assume you maintain the npmjs.com package.
How can we track the changes from npmjs's version 2.1.0 to 2.1.2 for instance?

Thanks!

**Comment by randdusing** [comment]
The plugin was renamed to [cordova-plugin-bluetoothle](https://www.npmjs.com/package/cordova-plugin-bluetoothle). The latest version on NPM is 2.4, same as the master branch in GitHub. You can see the current version in plugin.xml and see changes between versions in CHANGELOG.md. I'll see if I can put a deprecated message on the original plugin.
