### ISSUE TITLE
Use git tags to indicate versions

### ISSUE THREAD

**Issue by gortok** [randdusing/BluetoothLE#224]
Right now, any time someone pulls your plugin code; it's hard to tell which version is at which commit.  For instance, there are no tags or branches; and so an individual would have to search through the commits to find the various versions published to NPM.

Request that tags are created for each release so it's easier to track revisions of this plugin.

**Comment by randdusing** [comment]
@gortok Thanks for the suggestion. Just added one for the latest release and will keep creating them going forward.
