### ISSUE TITLE
ios not discover phone with android

### ISSUE THREAD

**Issue by langowskiadam** [randdusing/BluetoothLE#229]
Hello,
since few days I was trying to figure it out and I failed. When I use scan command it nor discover my android phone, but in my iPad bluetooth settings it is discovered (see screen bellow). I need only to get uuid, I don't want to connect/write etc - generally I only want to discover devices, which are in bluetooth range.

Please help.

Kind regards.
![1453276126373](https://cloud.githubusercontent.com/assets/4047675/12442944/6797c6a8-bf54-11e5-8293-c38c1eb47782.jpg)

**Comment by randdusing** [comment]
Unless there's an app that's advertising as a Bluetooth LE device running on the Android device, it won't show up while scanning. iOS Bluetooth settings shows any Bluetooth or Bluetooth LE device, while the scan only shows Bluetooth LE devices.
