### ISSUE TITLE
discover() on iOS?

### ISSUE THREAD

**Issue by tillz** [randdusing/BluetoothLE#63]
Hi there,
just a short question:
Do you have an idea why a cross-platform `discover()`-wrapper would be a bad idea?

If no, i'd implement a `combinedDiscover()`-method which simply calls `discover()` when used on android and `services()`, `characteristics()` & `descriptors()` when used on iOS.
I think it would be a good step do minimize platform-specific code.
Probably, the methods `services()`, `characteristics()` & `descriptors()` could be also made available on Android (via internally calling `discover()` and extracting the requested).
Even if this would be less performant, it would allow reusing the bluetooth-part of any app build upon this plugin for Android & iOS.

**Comment by quilkin** [comment]
Something like this would be very useful. I have an app working fine on Android but am having great difficulty working out the hierarchy of callbacks and storage for services, characteristics and descriptors.

**Comment by randdusing** [comment]
I'll look into adding this on my next update.

**Comment by quilkin** [comment]
Thanks. In the meantime, if anyone else has got the iOS discovery working, I'd be grateful for help with the JS for declaring the complex object needed for services/characteristics etc and how to store the characteristics once found.

**Comment by randdusing** [comment]
If you check out the returned object for discover on Android in the example, it should give you a good idea of how to store this information in an object.

**Comment by quilkin** [comment]
Actually I now discover that my object construct was OK. The problem was in timing, I was trying to subscribe to a service before all the characteristics callbacks had completed.
So now this is working; if anyone is interested I will make a more general version of my code and post it.

**Comment by cordphelps** [comment]
if you have time, it would help me. thanks!

**Comment by quilkin** [comment]
I've not made it very general but I have put the essence of what I've done into a separate file, see http://www.quilkin.co.uk/discover.js (I haven't got a github repo set up yet)
The discover function is called upon successful connection; the key function is characteristicsSuccess() which gets each characteristic recursively. 
I hope there's enough here for you; no apologies for any poor javascript!

**Comment by randdusing** [comment]
Started working on this today, and it should be ready sometime tomorrow. I need to add in some error handling and do some additional testing.

@quilkin Sorry, I was never able to check out the javascript. Hopefully some others got some good use out of it.

**Comment by randdusing** [comment]
Part of 2.4
